### ISSUE TITLE
 I get an error when compiling

### ISSUE THREAD

**Issue by actly** [second-state/SSVMRPC#2]
![image](https://user-images.githubusercontent.com/5006843/70592209-ee86f600-1c13-11ea-8c5c-9ae192ddd9ac.png)

**Comment by tpmccallum** [comment]
Hi @actly 
Sorry for the delayed response.
Please note that this is now resolved.
The new endpoints which are specified in the mount [1] have been updated.
This now compiles. Please let me know if you have any other questions.
[1] https://github.com/second-state/SSVMRPC/blob/master/rust/main.rs#L305
